# Generated by Django 6.0.1 on 2026-01-28 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Izdatel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название издателя', max_length=100, verbose_name='Название издателя')),
                ('geo', models.CharField(blank=True, help_text='Введите место регистрации издателя', max_length=120, null=True, verbose_name='Место регистрации издателя')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите статус экземпляра мебели', max_length=200, verbose_name='Статус экземпляра мебели')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите вид мебели', max_length=200, verbose_name='Вид мебели')),
            ],
        ),
        migrations.CreateModel(
            name='Mebel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название мебели', max_length=200, verbose_name='Название мебели')),
                ('summary', models.TextField(help_text='Введите краткое описание мебели', max_length=1000, verbose_name='Описание мебели')),
                ('size', models.CharField(help_text='Введите ширина*высота*глубина в сантиметрах', null=True)),
                ('izd', models.ForeignKey(help_text='Выберите издателя мебели', on_delete=django.db.models.deletion.CASCADE, to='myapp.izdatel', verbose_name='Издатель мебели')),
                ('type', models.ForeignKey(help_text='Выберите вид мебели', on_delete=django.db.models.deletion.CASCADE, to='myapp.type', verbose_name='Вид мебели')),
            ],
        ),
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_nom', models.CharField(help_text='Введите инвентарный номер мебели', max_length=20, null=True, verbose_name='Инвентарный номер мебели')),
                ('due_back', models.DateField(blank=True, help_text='Введите конец срока статуса', null=True, verbose_name='Дата окончания статуса')),
                ('mebel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.mebel')),
                ('status', models.ForeignKey(help_text='Изменить состояние экземпляра мебели', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.status')),
            ],
        ),
    ]
