# Generated by Django 6.0.1 on 2026-01-28 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='mebel',
            name='color',
            field=models.ForeignKey(help_text='Выберите цвет мебели', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.color', verbose_name='Цвет мебели'),
        ),
    ]
