# Generated by Django 6.0.1 on 2026-02-12 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_mebel_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='mebel',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Введите цену в рублях', max_digits=10, null=True, verbose_name='Цена'),
        ),
    ]
