# Generated by Django 6.0.1 on 2026-02-14 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_mebel_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='mebel',
            name='image',
            field=models.URLField(blank=True, help_text='Введите URL изображения', max_length=500, null=True, verbose_name='URL изображения'),
        ),
    ]
