# Generated by Django 6.0.1 on 2026-03-04 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_mebel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='mebel',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Введите кол-во товара в наличии', max_digits=10, null=True, verbose_name='Товара в наличии'),
        ),
    ]
