# Generated by Django 6.0.1 on 2026-03-11 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_cart_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='mebel',
        ),
        migrations.RemoveField(
            model_name='mebel',
            name='value',
        ),
        migrations.AddField(
            model_name='mebel',
            name='quantity',
            field=models.PositiveIntegerField(default=0, help_text='Введите количество товара в наличии', verbose_name='Количество'),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
