# Generated by Django 6.0.1 on 2026-07-04 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
